resilience4j:
    retry:
        configs:
            default:
                maxAttempts: 3
                waitDuration: 100ms
                retryExceptions:
                    - org.springframework.web.client.HttpServerErrorException
        instances:
            greetingRetry:
                baseConfig: default