management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always
management.health.diskspace.enabled: false
management.health.circuitbreakers.enabled: true
management.health.ratelimiters.enabled: false
management.metrics.tags.application: servicea
management.metrics.distribution.percentiles-histogram.http.server.requests: true
management.metrics.distribution.percentiles-histogram.resilience4j.circuitbreaker.calls: true

resilience4j:
    circuitbreaker:
        configs:
            default:
                slidingWindowSize: 10
                slidingWindowType: COUNT_BASED
                minimumNumberOfCalls: 5
                permittedNumberOfCallsInHalfOpenState: 3
                automaticTransitionFromOpenToHalfOpenEnabled: true
                waitDurationInOpenState: 10s
        instances:
            greetingCircuit:
                baseConfig: default
                failureRateThreshold: 50
                recordExceptions:
                    - org.springframework.web.client.HttpServerErrorException